apiVersion : apps/v1
kind: Deployment
metadata:
  name: "uleciiaaks-4928"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "uleciiaaks-4928"
  template:
    metadata:
      labels:
        app: "uleciiaaks-4928"
    spec:
      containers:
        - name: "uleciiaaks-4928"
          image: "uleciiacontainerregistry.azurecr.io/uleciiaaks"
          ports:
          - containerPort: 80