apiVersion: v1
kind: Service
metadata:
    name: "uleciiaaks-4928"
    labels:
        app: "uleciiaaks-4928"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "uleciiaaks-4928"